### ISSUE TITLE
Add Assertion constructors for common types

### ISSUE THREAD

**Issue by chuwy** [axiomed/Specs.lean#1]
If we're going to port what we have in `Http.lean` and `CaseInsensitive.lean` I think it would be useful to add some `Assertion` constructors for common cases. For example, we'd be able to write:

```lean
  Assertion.isEmpty "something should be empty"
    produceSomething
```

Instead of current:

```lean
  Assertion.make "something should be empty"
    true
    produceSomething
```

Other possible constructors:

- `isGreaterThan`
- `isLessThan`
- `isNonEmpty`
- `isSome` for `Option`

Also `isEqual` is relatively useless, because we can't produce a sensible diff if the resulting expression is just `Bool`. Maybe we can with macro, but I don't know how to write them yet.

**Comment by algebraic-dev** [comment]
Added a bunch of them :)
